resources:
    ProjetNormandie\UserBundle\Entity\User:
        collectionOperations:
            get:
                normalization_context: {'groups': [user.get]}
            profile:
                method: 'GET'
                access_control: 'is_granted("IS_AUTHENTICATED_FULLY")'
                normalization_context: {'groups': [user.profile]}
                path: '/users/profile'
                controller: 'ProjetNormandie\UserBundle\Controller\AuthController::profile'
            autocomplete:
                method: 'GET'
                normalization_context: {'groups': [user.autocomplete]}
                path: '/users/autocomplete'
                swagger_context:
                    parameters:
                        - name: query
                          in: query
                          required: true
                          type: string
                controller: 'ProjetNormandie\UserBundle\Controller\UserController::autocomplete'
            roles:
                method: 'GET'
                path: '/users/roles'
                controller: 'ProjetNormandie\UserBundle\Controller\AuthController::roles'
            registration-register:
                method: 'POST'
                path: '/users/registration/register'
                swagger_context:
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - username
                              properties:
                                  username:
                                      type: string
                controller: 'ProjetNormandie\UserBundle\Controller\RegistrationController::register'
            registration-confirm:
                method: 'POST'
                path: '/users/registration/confirm'
                swagger_context:
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - token
                              properties:
                                  token:
                                      type: string
                controller: 'ProjetNormandie\UserBundle\Controller\RegistrationController::confirm'
            resetting-send-email:
                method: 'POST'
                path: '/users/resetting/send-email'
                swagger_context:
                    parameters:
                        - in: body
                          name: user
                          schema:
                              type: object
                              required:
                                  - username
                                  - email
                                  - password
                              properties:
                                  username:
                                      type: string
                                  email:
                                      type: string
                                  password:
                                      type: string
                controller: 'ProjetNormandie\UserBundle\Controller\ResettingController::sendEmail'
            resetting-reset:
                method: 'POST'
                path: '/users/resetting/reset'
                description: tata
                swagger_context:
                    parameters:
                      - in: body
                        name: user
                        schema:
                            type: object
                            required:
                              - token
                              - paswword
                            properties:
                                token:
                                    type: string
                                password:
                                    type: string
                controller: 'ProjetNormandie\UserBundle\Controller\ResettingController::reset'
            upload-avatar:
                access_control: 'is_granted("ROLE_USER")'
                method: 'POST'
                path: '/users/upload-avatar'
                consumes:
                    - application/json
                swagger_context:
                    parameters:
                        - in: body
                          name: file
                          description: Picture encoded in base64
                          schema:
                              type: object
                              required:
                                  - base64
                              properties:
                                  base64:
                                      type: string
                controller: 'ProjetNormandie\UserBundle\Controller\AvatarController::upload'
        itemOperations:
            get:
                normalization_context: {'groups': [user.get]}
            put:
                access_control: 'is_granted("ROLE_USER") and object == user'
                denormalization_context: {'groups': [user.put]}
                normalization_context: {'groups': [user.get]}