services:
    sonata.admin.user.user:
        class: ProjetNormandie\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UserBundle", label: "User" }
        arguments:
            - ~
            - ProjetNormandie\UserBundle\Entity\User
            - ~
    sonata.admin.user.group:
        class: ProjetNormandie\UserBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UserBundle", label: "Group" }
        arguments:
            - ~
            - ProjetNormandie\UserBundle\Entity\Group
            - ~
    sonata.admin.user.ip:
        class: ProjetNormandie\UserBundle\Admin\IpAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UserBundle", label: "Ip" }
        arguments:
            - ~
            - ProjetNormandie\UserBundle\Entity\Ip
            - ~
