ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
        - 'user.get'
        - 'user.put'
        - 'user.read.mini'
    email:
      groups: []
    status:
      groups:
        - 'user.status'
    username:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
        - 'user.get'
        - 'user.read.mini'
    slug:
      groups:
        - 'user.profile'
        - 'user.get'
        - 'user.read.mini'
    locale:
      groups:
        - 'user.get'
        - 'user.put'
    groups:
      groups:
    firstName:
      groups:
        - 'user.get'
        - 'user.put'
    lastName:
      groups:
        - 'user.get'
        - 'user.put'
    birthDate:
      groups:
        - 'user.get'
        - 'user.put'
    country:
      groups:
        - 'user.profile'
        - 'user.get'
        - 'user.put'
    gender:
      groups:
        - 'user.profile'
        - 'user.get'
        - 'user.put'
    personalWebSite:
      groups:
        - 'user.get'
        - 'user.put'
    youtube:
      groups:
        - 'user.get'
        - 'user.put'
    twitch:
      groups:
        - 'user.get'
        - 'user.put'
    nbConnexion:
      groups:
        - 'user.profile'
