ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
    email:
      groups: []
    username:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
    locale:
      groups:
        - 'user.profile'
    groups:
      groups:
    firstName:
      groups:
        - 'user.profile'
    lastName:
      groups:
        - 'user.profile'
    nbConnexion:
      groups:
        - 'user.profile'
    badges:
      groups:
        - 'user.badges'
