services:
  sonata.admin.user.user:
    class: ProjetNormandie\UserBundle\Admin\UserAdmin
    tags:
      - name: sonata.admin
        model_class: 'ProjetNormandie\UserBundle\Entity\User'
        manager_type: orm
        group: "group.users"
        label: "label.user"
        label_translator_strategy: "sonata.admin.label.strategy.underscore"
  sonata.admin.user.group:
    class: ProjetNormandie\UserBundle\Admin\GroupAdmin
    tags:
      - name: sonata.admin
        model_class: 'ProjetNormandie\UserBundle\Entity\Group'
        manager_type: orm
        group: "group.users"
        label: "label.group"
        label_translator_strategy: "sonata.admin.label.strategy.underscore"
  sonata.admin.user.security_event:
    class: ProjetNormandie\UserBundle\Admin\SecurityEventAdmin
    tags:
      - name: sonata.admin
        model_class: 'ProjetNormandie\UserBundle\Entity\SecurityEvent'
        manager_type: orm
        group: "group.users"
        label: "Security Events"
        label_translator_strategy: "sonata.admin.label.strategy.underscore"
    calls:
      - [ setTemplate, [ 'show', '@@ProjetNormandieUser/Admin/security_event_show.html.twig' ] ]
