services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\UserBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  app.event.entity.user:
    class: ProjetNormandie\UserBundle\EventListener\Entity\UserListener
    tags:
      - { name: doctrine.orm.entity_listener }