ProjetNormandie\UserBundle\Entity\Group:
  attributes:
    id:
      groups:
        - 'user.profile'
    name:
      groups:
        - 'user.profile'
    roles:
      groups:
        - 'user.profile'
