ProjetNormandie\UserBundle\Entity\Status:
  attributes:
    id:
      groups:
        - 'user.status.read'
    class:
      groups:
        - 'user.status.read'
    name:
      groups:
        - 'user.status.read'