ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
        - 'user.get'
        - 'user.put'
        - 'user.read.mini'
    email:
      groups: []
    username:
      groups:
        - 'user.profile'
        - 'user.autocomplete'
        - 'user.get'
        - 'user.read.mini'
    slug:
      groups:
        - 'user.profile'
        - 'user.get'
        - 'user.read.mini'
    locale:
      groups:
        - 'user.get'
        - 'user.put'
    groups:
      groups:
    nbConnexion:
      groups:
        - 'user.profile'
